name: Build FastAPI Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::792171318913:role/FredBallFrontEndGitHubActionsRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-2

      - name: Upload Index to S3
        run: aws s3 cp index.html s3://${{ vars.S3_BUCKET }}/index.html 

